<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Eric Armstrong">

<title>Regression Modeling &amp; Forecasts: Egg Prices &amp; Their Potential Relation to Tariffs</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Final Tariff Presentation_files/libs/clipboard/clipboard.min.js"></script>
<script src="Final Tariff Presentation_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Final Tariff Presentation_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Final Tariff Presentation_files/libs/quarto-html/popper.min.js"></script>
<script src="Final Tariff Presentation_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Final Tariff Presentation_files/libs/quarto-html/anchor.min.js"></script>
<link href="Final Tariff Presentation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Final Tariff Presentation_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Final Tariff Presentation_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Final Tariff Presentation_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Final Tariff Presentation_files/libs/bootstrap/bootstrap-95cc2986dc35bc86795dce5a625ee777.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Index</h2>
   
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#logistics" id="toc-logistics" class="nav-link" data-scroll-target="#logistics">Logistics</a></li>
  <li><a href="#notable-regression-models" id="toc-notable-regression-models" class="nav-link" data-scroll-target="#notable-regression-models">Notable Regression Models</a></li>
  <li><a href="#eda-correlation-models" id="toc-eda-correlation-models" class="nav-link" data-scroll-target="#eda-correlation-models">EDA &amp; Correlation Models</a></li>
  <li><a href="#relevant-forecasts-inferences-based-off-them" id="toc-relevant-forecasts-inferences-based-off-them" class="nav-link" data-scroll-target="#relevant-forecasts-inferences-based-off-them">Relevant Forecasts &amp; Inferences Based Off Them</a></li>
  <li><a href="#correlation-grid" id="toc-correlation-grid" class="nav-link" data-scroll-target="#correlation-grid">Correlation Grid</a></li>
  <li><a href="#key-takeaways-final-conclusions" id="toc-key-takeaways-final-conclusions" class="nav-link" data-scroll-target="#key-takeaways-final-conclusions">Key Takeaways &amp; Final Conclusions</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression Modeling &amp; Forecasts: Egg Prices &amp; Their Potential Relation to Tariffs</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Eric Armstrong </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Over the course of the past 2 weeks, my work primarily consisted of building an OLS Regression Model to track how egg prices impacted consumption, with a specific focus on consumer spending patterns. This project’s main goal was to track how egg consumption (the predictor variable) acted in relation to the prices of eggs, while also finding which combination of external factors (the control variables) would provide the strongest statistical model. Below, I showcase a few of my most notable findings, and the models which I believe are most useful to VISA.</p>
</section>
<section id="logistics" class="level2">
<h2 class="anchored" data-anchor-id="logistics">Logistics</h2>
<p>All data is public and was pulled from the US Census Bureau, and the Bureau of Economic Analysis (BEA). The data is monthly and begins coverage from 01-01-2018 to 05-01-2025.<br>
<br>
Below is a key for what each coefficient in the data stands for:</p>
<p>UFMEN: CPI-U: Eggs&nbsp; (NSA, 1982-84=100)</p>
<p>UFEC: CPI-U: Real Personal Egg Consumption Expenditures, Chained Dollars (SA)</p>
<p>PCE: Personal consumption expenditures</p>
<p>VSMINN: Visa Nondiscretionary Spending Momentum Index (NSA, &gt;100=Strengthening)</p>
<p>VSMIDN: Visa Discretionary Spending Momentum Index (NSA, &gt;100=Strengthening)</p>
<p>CCOND: University of Michigan: Current Economic Conditions (NSA, Q1-66=100)</p>
<p>RECPROB: Probability of US Recession 12-Mo Ahead, as Predicted by the Treasury Spread (%)</p>
<p>PXEA: Export Price Index: All Exports (NSA, 2000=100)</p>
<p>PMEA: Import Price Index: All Imports (NSA, 2000=100)</p>
<p>NRSI511N: Retail Sales: Supermarkets &amp; Other Grocery [ex Convenience Stores](NSA, Mil.US$)</p>
<p>NRSV2N: Retail Sales: Food Services &amp; Drinking Places (NSA, Mil.$)</p>
<p>Education: Real Personal Consumption Expenditures, Chained Dollars for Education</p>
<p>FNBOPC: Food and beverages purchased for off-premises consumption</p>
</section>
<section id="notable-regression-models" class="level2">
<h2 class="anchored" data-anchor-id="notable-regression-models">Notable Regression Models</h2>
<p>The following regression model provided me with the highest R^2 value of .989, or 98.9% of the variance in the data could be explained by the model, making it very statistically powerful. For control variables, I used PCE, VSMINN, VSMIDN, CCOND, RECPROB, PXEA, PMEA, NRSI511N, Education and FNBOPC.</p>
<div id="a67a2cb6" class="cell" data-execution_count="1">
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  UFMEN   R-squared:                       0.989
Model:                            OLS   Adj. R-squared:                  0.981
Method:                 Least Squares   F-statistic:                     125.3
Date:                Thu, 17 Jul 2025   Prob (F-statistic):           2.33e-13
Time:                        10:31:54   Log-Likelihood:                -96.402
No. Observations:                  28   AIC:                             216.8
Df Residuals:                      16   BIC:                             232.8
Df Model:                          11                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   -366.3047    696.982     -0.526      0.606   -1843.840    1111.231
UFEC          -0.0353      0.003    -12.619      0.000      -0.041      -0.029
PCE        -5.991e-05   5.52e-05     -1.086      0.294      -0.000    5.71e-05
VSMINN        -6.8505      1.779     -3.850      0.001     -10.623      -3.078
CCOND          0.2126      0.381      0.558      0.585      -0.595       1.020
RECPROB       -0.4606      0.399     -1.154      0.266      -1.307       0.386
PXEA           9.3287      2.669      3.496      0.003       3.671      14.986
PMEA         -15.0154      4.080     -3.680      0.002     -23.664      -6.367
NRSI511N       0.0005      0.001      0.366      0.719      -0.002       0.003
VSMIDN         3.1015      1.235      2.512      0.023       0.484       5.719
Education      0.0051      0.003      2.018      0.061      -0.000       0.011
FNBOPC         0.0013      0.001      1.681      0.112      -0.000       0.003
==============================================================================
Omnibus:                        1.464   Durbin-Watson:                   2.140
Prob(Omnibus):                  0.481   Jarque-Bera (JB):                0.694
Skew:                          -0.374   Prob(JB):                        0.707
Kurtosis:                       3.189   Cond. No.                     5.88e+09
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.88e+09. This might indicate that there are
strong multicollinearity or other numerical problems.</code></pre>
</div>
</div>
<section id="important-findings" class="level3">
<h3 class="anchored" data-anchor-id="important-findings">Important Findings</h3>
<ul>
<li><p>The p-value of our predictor variable, consumer spending on eggs, is nearly 0; signifies that there is extremely strong statistically significant evidence that consumer spending directly impacts the price of eggs.</p></li>
<li><p>Since our coefficient for the following variable is negative, we can infer that as the price of eggs rises, consumption rates slightly drop.<br>
</p></li>
<li><p>With respect to control variables, spending momentum and the export import index were the only variables which crossed the significance threshold of p &lt; 0.05. Education with a p-value of 0.061 was very close, however the p-value was a little too large to meet the statistically significant benchmark.</p></li>
<li><p>We can infer that there is statistically significant evidence that spending momentum, alongside export and import index rates affect the price of eggs.</p></li>
</ul>
</section>
<section id="slight-problem-multicollinearity-overfitting" class="level3">
<h3 class="anchored" data-anchor-id="slight-problem-multicollinearity-overfitting">Slight Problem: Multicollinearity &amp; Overfitting</h3>
<p>While the following model was able to push out such a high R^2 value, there were some glaring issues with the model which could not be overlooked, with the main one being the super high condition number suggesting the presence of multicollinearity. To combat this issue, I conducted a VIF test on my parameters to see which ones were not absolutely necessary for the regression model. Below is the redesigned model alongside the VIF testing results to illustrate which parameters were causing issues.</p>
<div id="84a529d4" class="cell" data-execution_count="2">
<div class="cell-output cell-output-stdout">
<pre><code>
=== Variance Inflation Factors ===
   Variable       VIF
8    NRSV2N  3.606692
4  NRSI511N  3.409403
3      PXEA  2.916845
2      PMEA  2.852967
9    VSMIDN  2.292265
7    VSMINN  1.981429
6     CCOND  1.611814
5      CCIN  1.364587
1      UFEC  1.214003
0     const  1.071134
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   UFME   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.919
Method:                 Least Squares   F-statistic:                     33.93
Date:                Thu, 17 Jul 2025   Prob (F-statistic):           4.00e-09
Time:                        10:31:54   Log-Likelihood:                 75.676
No. Observations:                  27   AIC:                            -131.4
Df Residuals:                      17   BIC:                            -118.4
Df Model:                           9                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.0056      0.004      1.523      0.146      -0.002       0.013
UFEC          -0.9416      0.058    -16.270      0.000      -1.064      -0.820
PMEA           1.5993      1.399      1.143      0.269      -1.352       4.551
PXEA          -0.6773      0.808     -0.838      0.414      -2.382       1.028
NRSI511N      -0.1056      0.131     -0.803      0.433      -0.383       0.172
CCIN          -0.0496      0.087     -0.573      0.574      -0.232       0.133
CCOND          0.0641      0.066      0.965      0.348      -0.076       0.204
VSMINN         0.2696      0.258      1.047      0.310      -0.274       0.813
NRSV2N         0.1615      0.105      1.543      0.141      -0.059       0.382
VSMIDN        -0.3110      0.194     -1.603      0.127      -0.720       0.098
==============================================================================
Omnibus:                        1.899   Durbin-Watson:                   2.109
Prob(Omnibus):                  0.387   Jarque-Bera (JB):                0.821
Skew:                          -0.371   Prob(JB):                        0.663
Kurtosis:                       3.423   Cond. No.                         433.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
</section>
<section id="brief-summary-of-findings" class="level3">
<h3 class="anchored" data-anchor-id="brief-summary-of-findings">Brief Summary of Findings:</h3>
<ul>
<li><p>None of the values in the VIF table fall above 3.6 &lt; 10, signifying that all the following indices should not cause any issues of multicollinearity.</p></li>
<li><p>The high R^2 value of .947 signifies that the model is strong, as 94.7% of the variance in the data can be explained by it.</p></li>
<li><p>Just like the last model, we see the super low p-value of nearly 0 for the egg consumption variable, reinforcing the statistical significance and negative correlation which egg consumption has on its prices.</p></li>
<li><p>unlike the previous model, none of the control coefficients p-values fall under the significance threshold of p &lt; 0.05, so there is not enough statistically significant evidence to reject the null hypothesis for any of these factors.</p></li>
</ul>
<p>Finally, I included a residual plot below as a final test to confirm the model met all conditions safely. Since the residuals are randomly spread with no pattern, this confirms the model should be accurate without any issues of multicollinearity.</p>
<div id="64fc8b9b" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final%20Tariff%20Presentation_files/figure-html/cell-4-output-1.png" width="400" height="277" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="eda-correlation-models" class="level2">
<h2 class="anchored" data-anchor-id="eda-correlation-models">EDA &amp; Correlation Models</h2>
<div id="ebc3a871" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final%20Tariff%20Presentation_files/figure-html/cell-5-output-1.png" width="712" height="423" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="a8245cc2" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final%20Tariff%20Presentation_files/figure-html/cell-6-output-1.png" width="327" height="231" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>The following two graphs illustrate the negative correlation between the price of eggs, and consumer spending patterns.</p></li>
<li><p>As the price of eggs increases, consumer spending drops and vice versa.</p></li>
</ul>
<div id="24237c42" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final%20Tariff%20Presentation_files/figure-html/cell-7-output-1.png" width="712" height="423" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="4851e066" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final%20Tariff%20Presentation_files/figure-html/cell-8-output-1.png" width="712" height="423" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Export index and egg prices closely track each other, shows the positive correlation.</p></li>
<li><p>Import index is a little more variate, but negative correlation between the two can be visibly seen over some quarterly spans just as the regression model suggested.</p></li>
</ul>
</section>
<section id="relevant-forecasts-inferences-based-off-them" class="level2">
<h2 class="anchored" data-anchor-id="relevant-forecasts-inferences-based-off-them">Relevant Forecasts &amp; Inferences Based Off Them</h2>
<p>Below, I included some forecast graphs which I believed were relevant to the project. I chose indices within the regression model that may give us further insight about how consumer spending patterns and the prices of eggs may change in the future. Additionally, I also tried to synthesize the information with the recent tariff changes, as this was a strong point of interest for Publix.</p>
<section id="egg-prices" class="level3">
<h3 class="anchored" data-anchor-id="egg-prices">Egg Prices</h3>
<div id="567afc9e" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stderr">
<pre><code>10:31:56 - cmdstanpy - INFO - Chain [1] start processing
10:31:56 - cmdstanpy - INFO - Chain [1] done processing</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final%20Tariff%20Presentation_files/figure-html/cell-10-output-2.png" width="712" height="423" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final%20Tariff%20Presentation_files/figure-html/cell-10-output-3.png" width="638" height="423" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Egg prices have been on the steady, very subtle rise prior to the 2025 shortage</p></li>
<li><p>Around the end of 2024 and the beginning of 2025, we see the huge price jump in eggs which was caused by the bird flu.</p></li>
<li><p>From this graph, prophet estimates that egg prices may potentially jump super high, but more generally will still steadily increase</p></li>
<li><p>Signifies prices will not be permanently damaged by the shortage.</p></li>
</ul>
</section>
<section id="retail-sales-for-supermarkets-other-grocery-stores" class="level3">
<h3 class="anchored" data-anchor-id="retail-sales-for-supermarkets-other-grocery-stores">Retail Sales for Supermarkets &amp; Other Grocery Stores</h3>
<div id="bb7593aa" class="cell" data-execution_count="10">
<div class="cell-output cell-output-stderr">
<pre><code>10:31:57 - cmdstanpy - INFO - Chain [1] start processing
10:31:57 - cmdstanpy - INFO - Chain [1] done processing</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final%20Tariff%20Presentation_files/figure-html/cell-11-output-2.png" width="713" height="423" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final%20Tariff%20Presentation_files/figure-html/cell-11-output-3.png" width="638" height="423" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="retail-sales-for-food-services-drinking-places" class="level3">
<h3 class="anchored" data-anchor-id="retail-sales-for-food-services-drinking-places">Retail Sales for Food Services &amp; Drinking Places</h3>
<div id="5ffdc3bc" class="cell" data-execution_count="11">
<div class="cell-output cell-output-stderr">
<pre><code>10:31:58 - cmdstanpy - INFO - Chain [1] start processing
10:31:58 - cmdstanpy - INFO - Chain [1] done processing</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final%20Tariff%20Presentation_files/figure-html/cell-12-output-2.png" width="712" height="423" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final%20Tariff%20Presentation_files/figure-html/cell-12-output-3.png" width="638" height="423" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Retail sales for Supermarkets &amp; Other Grocery Stores compared to retail sales for Food Services shared similar constant rising path.</p></li>
<li><p>Main difference between the two is grocery and supermarket sales project on a much more constant growth line whereas restaurants and other food services are affected more heavily by widescale events (COVID in 2020 resulting in drop).</p></li>
<li><p>Best explained by the fact that grocery store products are usually necessities, whereas restaurant sales are more oriented towards consumer preference (luxury goods), making the graph more volatile.</p></li>
</ul>
</section>
<section id="import-price-index" class="level3">
<h3 class="anchored" data-anchor-id="import-price-index">Import Price Index</h3>
<div id="8bc953f9" class="cell" data-execution_count="12">
<div class="cell-output cell-output-stderr">
<pre><code>10:31:59 - cmdstanpy - INFO - Chain [1] start processing
10:31:59 - cmdstanpy - INFO - Chain [1] done processing</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final%20Tariff%20Presentation_files/figure-html/cell-13-output-2.png" width="712" height="423" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final%20Tariff%20Presentation_files/figure-html/cell-13-output-3.png" width="638" height="423" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="export-price-index" class="level3">
<h3 class="anchored" data-anchor-id="export-price-index">Export Price Index</h3>
<div id="a287f4c8" class="cell" data-execution_count="13">
<div class="cell-output cell-output-stderr">
<pre><code>10:32:00 - cmdstanpy - INFO - Chain [1] start processing
10:32:00 - cmdstanpy - INFO - Chain [1] done processing</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final%20Tariff%20Presentation_files/figure-html/cell-14-output-2.png" width="712" height="423" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final%20Tariff%20Presentation_files/figure-html/cell-14-output-3.png" width="638" height="423" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Both the import and export indexes share similar forecast paths, including the huge jump around 2020.</p></li>
<li><p>In 2018, President Donald Trump implemented very similar tariffs on steel and aluminum to the current actions we are seeing today. The forecast graph for both imports and exports shows how there was a recession around the year 2018, but after the tariff war ended and Trump left office, rapid amounts of growth came with it.</p></li>
<li><p>While the tariffs today are much larger in scale compared to 2018, if we use 2018 as a precedent, we can expect a drop in exports and imports followed by massive growth once a change in office occurs.</p></li>
<li><p>Prophet’s forecast still predicts stable growth will occur in both models although the data is variable.</p></li>
</ul>
</section>
</section>
<section id="correlation-grid" class="level2">
<h2 class="anchored" data-anchor-id="correlation-grid">Correlation Grid</h2>
<p>Below I attached a large grid of all the correlations between variables in the regression models. Deeper shades of blue signify stronger positive correlation while deeper shades of red signify stronger negative correlation between variables. Light white shades signify almost no correlation and a black shade signifies that there is not enough data to come to a statistical conclusion.</p>
<div id="a4ddb238" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final%20Tariff%20Presentation_files/figure-html/cell-15-output-1.png" width="279" height="231" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="key-takeaways-final-conclusions" class="level2">
<h2 class="anchored" data-anchor-id="key-takeaways-final-conclusions">Key Takeaways &amp; Final Conclusions</h2>
<ul>
<li><p>Egg Prices and consumer spending had a high correlation and high statistical significance in every single model, these two variables directly affect each other</p></li>
<li><p>Spending momentum and international trade (import export index) came up as the most statistically significant control variables, they very likely have an effect on the prices of eggs</p></li>
<li><p>Egg prices will not be permanently damaged by the shortage despite it being so extreme; prophet predicts growth will eventually level out back to normal</p></li>
<li><p>Restaurant spending is much more volatile than grocery stores in predicted models. This is best explained by the fact that grocery stores primarily sell necessities whereas restaurants are more oriented towards luxury consumer preference</p></li>
<li><p>COVID mark in 2020 illustrates that large-scale global events usually do not affect sales on everyday essential items</p></li>
<li><p>The import export forecasts provide us with useful models that can be used as a precedent for Trump’s new wave of tariffs in 2025. We see the steady decline in imports and exports as a result of Trump’s time in office from 2018 to 2020, then the rapid growth after the change in office and COVID’s conclusion</p></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="Final Tariff Presentation_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>